from django.db import models

from rooms.models import Room, Building
from accounts.models import User, Trainee, TrainingAssistant
from terms.models import Term

""" ROOM RESERVATIONS models.py

The ROOMS RESERVATIONS app represents reservations that are made for the various locations
of the training. They are made by trainees or TA's and approved by TA's. Both trainees and
TA's use the reservation schedule generated by this app.

Data Models:
    - Reservation: a reservation for a particular room at a given time.

"""


class Reservation(models.Model):

	# room reserved
    room = models.ForeignKey(Room)

    # description of the group, e.g., ANA-COM, Children's Team, Clean-up Stars
    use_by = models.CharField(max_length=30)

    # approximate size of group
    group_size = models.IntegerField(default=25)

    # description of usage, e.g., "Fourth-term fellowship with brother X"
    description = models.CharField(max_length=100)

    # reservation approval status
    status = models.BooleanField(default=False)

    # time of reservation request submission
    timestamp = models.DateTimeField(auto_now=True)

    # recurrence? T = all-term recurrence, F = only once
    repeat = models.BooleanField(default=False)

    # starting time
    # ending time
    # currently looking into extending EventGroup to create repeating events...





